[quaeros]
    [quaeros.assets]
        [quaeros.assets.styles]
            head = [ "base" ]
            foot = [ "base" ]
        [quaeros.assets.script]
            head = [ "main" ]
            foot = [ "main" ]

